version: '3'

networks:
    php-net:
        
services:

    ####################################################################################################
    # PHP
    ####################################################################################################
    php:
        container_name: mvc_php
        build: .docker/php
        ports:
            - 5174:5174
        volumes:
            - .:/var/www:cached
        networks:
            - php-net

    ####################################################################################################
    # Nginx
    ####################################################################################################
    nginx:
        container_name: mvc_nginx
        image: nginx
        ports:
            - 8002:80
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php
        networks:
            - php-net

