version: '3'

networks:
    php-net:

volumes:
    php-mysql-db:
        name: 'php-mysql-db'
        
services:

    ####################################################################################################
    # PHP
    ####################################################################################################
    php:
        container_name: mvc_php
        build: .docker/php
        ports:
            - 5174:5174
        volumes:
            - .:/var/www:cached
        networks:
            - php-net

    ####################################################################################################
    # Nginx
    ####################################################################################################
    nginx:
        container_name: mvc_nginx
        image: nginx
        ports:
            - 8002:80
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php
        networks:
            - php-net

    ####################################################################################################
    # Mysql
    ####################################################################################################
    db:
        image: 'mysql:8.0.31'
        command:
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
        - --default-authentication-plugin=mysql_native_password
        - --local-infile=1
        - --secure-file-priv=/sqls
        environment:
            MYSQL_ROOT_PASSWORD: secret
        volumes:
        - php-mysql-db:/var/lib/mysql
        - .docker/mysql/sqls:/sqls
        networks:
            php-net:
                aliases:
                    - php-mysql
        ports:
            - 3306:3306

